---
- name: VFLOW Configuration
  hosts: spine[0]

  tasks:
    - name: VFLOW Configuration
      pn_vflow:
        pn_cliusername:	"{{ USERNAME }}"					#Provide login username if user is not root.
        pn_clipassword:	"{{ PASSWORD }}"					#Provide login password if user is not root.
        pn_cliswitch: "uans-9kspine1"						#Target switch to run the CLI on.
        pn_action: "create"						#vFlow configuration command.
        pn_name: "spine1TCPvFlow"						#Name for the vFlow.
        pn_scope: "fabric"						#Scope is local or fabric.
        #pn_vflow_id:						#ID assigned to the vFlow.
        #pn_vnet:						#VNET assigned to the vFlow.
        #pn_l2net:						#l2-net for the vFlow.
        #pn_vlan:						#VLAN for the vFlow.
        #pn_inport:						#Incoming port for the vFlow.
        #pn_outport:						#Outgoing port for the vFlow.
        #pn_ether_type:						#EtherType for the vFlow.
        #pn_src_mac:						#Source MAC address for the vFlow.
        #pn_src_mac_mask:						#Source MAC address to use as a wildcard mask.
        #pn_dst_mac:						#Destination MAC address for the vFlow.
        #pn_dst_mac_mask:						#Destination MAC address to use as a wildcard mask.
        pn_src_ip: "10.10.10.1"						#Source IP address for the vFlow.
        pn_src_ip_mask: "24"						#Source IP address wildcard mask for the vFlow.
        #pn_dst_ip:						#Destination IP address for the vFlow.
        #pn_dst_ip_mask:						#Destination IP address wildcard mask for the vFlow.
        #pn_src_port:						#Layer 3 protocol source port for the vFlow.
        #pn_src_port_mask:						#Source port mask.
        #pn_dst_port:						#Layer 3 protocol destination port for the vFlow.
        #pn_dst_port_mask:						#Destination port mask.
        #pn_dscp_start:						#6bit Differentiated Services Code Point (DSCP) start number.
        #pn_dscp_end:						#6bit Differentiated Services Code Point (DSCP) end number.
        #pn_dscp:						#6bit Differentiated Services Code Point (DSCP)
        #pn_dscp_map:						#DSCP map to apply on the flow. Please reapply
        #pn_tos_start:						#Start Type of Service (ToS) number.
        #pn_tos_end:						#The ending Type of Service (ToS) number.
        #pn_tos:						#ToS number for the vFlow.
        #pn_vlan_pri:						#Priority for the VLAN 0 to 7.
        #pn_ttl:						#Time-to-live.
        pn_proto: "tcp"						#Layer 3 protocol for the vFlow.
        pn_tcp_flags: "syn"						#TCP Control Flags.
        #pn_flow_class:						#vFlow class name.
        #pn_ingress_tunnel:						#Tunnel for the ingress traffic.
        #pn_egress_tunnel:						#Tunnel for egress traffic.
        #pn_bw_min:						#Minimum bandwidth in Gbps.
        #pn_bw_max:						#Maximum bandwidth in Gbps.
        #pn_burst_size:						#Committed burst size in bytes.
        #pn_vrouter_name:						#Name of the vrouter service.
        #pn_precedence:						#Traffic priority value between 2 and 15.
        #pn_vflow_action:						#Forwarding action to apply to the vFlow.
        #pn_action_value:						#Optional value argument between 1 and 64.
        #pn_action_mac_value:						#MAC address value.
        #pn_action_nexthop_ip_value:						#Next-hop IP address for packet redirection.
        #pn_action_ports_value:						#Action to ports value.
        #pn_mirror:						#Mirror configuration name.
        #pn_process_mirror:						#vFlow processes mirrored traffic or not.
        #pn_log_packets:						#Log the packets in the flow.
        #pn_packet_log_max:						#Maximum packet count for log rotation in the flow.
        #pn_log_stats:						#Log packet statistics for the flow.
        #pn_stats_interval:						#Interval to update packet statistics for the log(seconds).
        #pn_dur:						#Minimum duration required for the flow to be captured(seconds).
        #pn_metadata:						#Metadata number for the vFlow.
        #pn_transient:						#Capture transient flows.
        #pn_vxlan_vlan:						#Name of the VXLAN.
        #pn_vxlan_ether_type:						#EtherType of the VXLAN.
        #pn_vxlan_proto:						#Protocol type for the VXLAN.
        #pn_set_src_ip:						#Set src ip of ipv4 packets.
        #pn_set_dst_ip:						#Set dst ip of ipv4 packets.
        #pn_set_src_port:						#Set src port of ipv4 packets.
        #pn_set_dst_port:						#Set dst port of ipv4 packets.
        #pn_udf_name1:						#Udf name.
        #pn_udf_data1:						#Udf data.
        #pn_udf_data1_mask:						#Mask for udf data.
        #pn_udf_name2:						#Udf name.
        #pn_udf_data2:						#Udf data.
        #pn_udf_data2_mask:						#Mask for udf data.
        #pn_udf_name3:						#Udf name.
        #pn_udf_data3:						#Udf data.
        #pn_udf_data3_mask:						#Mask for udf data.
        #pn_enable:						#Enable/disable flows in hardware.
        #pn_table_name:						#Table name.
        #pn_cpu_class:						#CPU class name.
      register: output
    - debug:
        var: output
