---
- name: vrouter interface config modules
  hosts: spine[0]

  tasks:
    - name: Add a vrouter interface config
      pn_vrouter_ifconfig:
        pn_cliusername: "{{ USERNAME }}"                #Provide login username if user is not root.
        pn_clipassword: "{{ PASSWORD }}"                       #Provide login password if user is not root.
        pn_cliswitch: "ansible-spine1"                  #Target switch to run the cli on.
        pn_action: "add"                                #vRouter interface command - add/remove/modify.
        pn_vrouter: "spine1-vrouter"            #Name of the vrouter.
        pn_nic: "eth0.101"                                        #Virtual NIC name.
        pn_ospf_hello_int: 10                             #OSPF hello interval from 1 to 65535, default 10.
        #pn_ospf_dead_int: 10                              #OSPF dead interval from 2 to 65535, default 5.
        pn_ospf_priority: 2                              #OSPF priority from 0 to 255, default 1.
        #pn_ospf_authkey:                                #OSPF authentication key.
        #pn_ospf_cost:                                   #OSPF Cost.
        #pn_ospf_msg_digestid:                           #OSPF digest ID from 0 to 255. Requires pn_ospf_msg_digestkey.
        #pn_ospf_msg_digestkey:                          #OSPF MSG digest key. Requires pn_ospf_msg_digestid.
        #pn_ospf_passive_if:                             #OSPF passive interface.
        #pn_ospf_network_type:                           #OSPF network type.
        pn_ospf_bfd: enable                                    #BFD protocol support for OSPF fault detection.
        #pn_bfd_interval:                                #BFD desired transmit interval from 200ms to 3000ms, default 750ms.
        #pn_bfd_min_rx:                                  #BFD desired minimum receive interval from 200ms to 3000ms, default
        #pn_bfd_multiplier:                              #BFD detection multiplier from 1 to 20, default 3.
        #pn_nd_suppress_ra:                              #Control transmit of IPv6 Router Advertisements.
        #pn_v6_ra_prefix:                                #IPv6 prefix to include in Router Advertisement.
        #pn_prefix_netmask:                              #v6 prefix netmask.
        #pn_autoconf:                                    #Given prefix can be used for IPv6 autoconf.
        #pn_ra_interval:                                 #Time interval between ipv6 router advertisements.
        #pn_ra_lifetime:                                 #Time for which router is considered as default router.
      register: output
    - debug:
        var: output
