#Vlan CSV Validation
---


- name: Validate Vlan CSV File
  hosts: localhost

  tasks:
    # This task is to validate vlan csv file.
    - name: Validate vlan config in csv file
      pn_vlan_csv_validation:
        pn_csv_data: "{{ lookup('file', '{{ vlan_csv_file }}') }}"
        pn_switch_list: "{{ groups['switch'] }}"
      register: csv_out

    # Playbook execution will fail if csv file is invalid.
    - fail:
        msg: "Invalid csv file"
      when: csv_out.failed == true
